BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "EventTypes" (
	"TypeID"	INTEGER NOT NULL,
	"Name"	TEXT,
	"Description"	TEXT,
	PRIMARY KEY("TypeID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "SensorEvents" (
	"EventID"	INTEGER NOT NULL,
	"TypeID"	INTEGER NOT NULL,
	"RecordID"	INTEGER NOT NULL,
	PRIMARY KEY("EventID" AUTOINCREMENT),
	FOREIGN KEY("RecordID") REFERENCES "SensorRecords"("RecordID"),
	FOREIGN KEY("TypeID") REFERENCES "EventTypes"("TypeID")
);
CREATE TABLE IF NOT EXISTS "SensorRecords" (
	"RecordID"	INTEGER NOT NULL,
	"DateTime"	DateTime NOT NULL,
	"Temperature"	REAL NOT NULL,
	"Pressure"	REAL NOT NULL,
	"Humidity"	REAL NOT NULL,
	PRIMARY KEY("RecordID" AUTOINCREMENT)
);
COMMIT;
